[package]
name = "stubs-gen"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "stubs-gen"
path = "stubs-gen.rs"

[dependencies]
ocaml-rs-smartptr = {path=".."}
ocaml-rs-smartptr-test = {path="../test"}
ocaml-gen = "*"
